### PR TITLE
Document starting with a percentage complete

### PR DESCRIPTION
**Pull request by nilbus**
Here's some documentation for that new feature.

### CODE REVIEW

**Comment by ConnorDoyle** [comment]
Edward, thank you very much for you contributions.  Soon I should have time to integrate your new features into the online demo and docs on the web site.

**Comment by nilbus** [comment]
I look forward to showing your what we do with it :-)

**Comment by ConnorDoyle** [comment]
## Pac man I hope :)

Connor

**Comment by nilbus** [comment]
Screencast: http://www.screenr.com/hiE8
:-D

**Pull request merged**
